name: Sync fork

on:
  schedule:
    - cron: "0 */1 * * *"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fork
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: repo-sync/github-sync@v2.3.0
        with:
          source_repo: "ecmwf/WeatherGenerator"
          source_branch: "tjh/dev/dashboard"
          destination_branch: "tjh/dev/dashboard"
          github_token: ${{ secrets.GITHUB_TOKEN }}
